build-job:
  image: docker:dind
  stage: build
  script:
    - echo "USER $USER CI_COMMIT_BRANCH $CI_COMMIT_BRANCH, GITLAB_USER_LOGIN $GITLAB_USER_LOGIN"
    - docker compose build
  services:
    - docker:dind

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

